### ISSUE TITLE
Написать docker-compose.yml конфиг для развертывания Postgres

### ISSUE THREAD

**Issue by didhat** [Haermeus-DevGroup/haermeus-server#3]
Это совсем не сложное задание. Нам для реализации проекта нужна будет база данных(мы выбрали Postgres). Разворачивать ее локально неудобно, поэтому мы будем использовать docker для быстрого и простого ее развертывания.

**Задача**: Написать конфиг файл(скопировать снизу и **понять** за что отвечает каждая строчка). Развернуть это у себя для теста. Делать это все в отдельной ветке, потом сделать merge request.
На очной встрече ещё обсудим эту задачу.
Конфиг для `docker-compose.yml`

```
version: "3.9"

services:
  postgres:
    container_name: postgres_db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_db
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
```
